
[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = ["minecraft", "alltheores", "kubejs", "mekanism", "create", "immersiveengineering", "thermal", "ae2", "ftbic", "biggerreactors"]

