
["Spiritcaller Settings"]
	#The Spiritcaller's damage will be multiplied by this number. Default: 2.5
	"Spiritcaller Damage Multiplier" = 2.5
	#Whether or not the Spiritcaller wears armor. Default: true
	"Spiritcaller Wears Armor" = true
	#Whether or not the Spiritcaller has a boss health bar. Default: true
	"Spiritcaller Has Boss Bar" = true
	#Whether or not any of the Spiritcaller's attacks are changed. Turning this off overrides all other Spiritcaller settings besides the previous 3. Default: true
	"Should Change Spiritcaller's Attacks At All" = true
	#Whether or not to change the Spiritcaller's Imp Rise. Default: true
	"Change Spiritcaller Imp Rise" = true
	#Whether or not to change the Spiritcaller's Soul Beam. Default: true
	"Change Spiritcaller Soul Beam" = true
	#Whether or not to change the Spiritcaller's Spirit Hands. Default: true
	"Change Spiritcaller Spirit Hands" = true
	#Whether or not to change the Spiritcaller's Soul Swarm. Default: true
	"Change Spiritcaller Soul Swarm" = true
	#Whether or not to spawn Imps periodically under the Spiritcaller's target. Default: true
	"Spawn Periodic Imps" = true
	#Whether or not to spawn souls when the Spiritcaller performs an attack. Default: true
	"Create Souls" = true
	#Whether or not to do Power Overwhelming (Phase 3) upon the Spiritcaller's first death. Default: true
	"Do Power Overwhelming" = true
	#How long in seconds Power Overwhelming (Phase 3) lasts. Default: 90
	"Power Overwhelming Duration" = 90

["Magispeller Settings"]
	#The Magispeller's damage will be multiplied by this number. Default: 2.5
	"Magispeller Damage Multiplier" = 2.5
	#Whether or not the Magispeller wears armor. Default: true
	"Magispeller Wears Armor" = true
	#Whether or not the Magispeller has a boss health bar. Default: true
	"Magispeller Has Boss Bar" = true
	#Whether or not any of the Magispeller's attacks are changed. Turning this off overrides all other Magispeller settings besides the previous 3. Default: true
	"Should Change Magispeller's Attacks At All" = true
	#Whether or not to change the Magispeller's Heal. Default: true
	"Change Magispeller Heal" = true
	#Whether or not to change the Magispeller's Vexes. Default: true
	"Change Magispeller Vexes" = true
	#Whether or not to change the Magispeller's Crossbow Spin. Default: true
	"Change Magispeller Crossbow Spin" = true
	#Whether or not to change the Magispeller's Potion Toss. Default: true
	"Change Magispeller Potion Toss" = true
	#Whether or not to change the Magispeller's Kaboomer. Default: true
	"Change Magispeller Kaboomer" = true
	#Whether or not to change the Magispeller's Lifesteal. Default: true
	"Change Magispeller Lifesteal" = true
	#Whether or not to change the Magispeller's Fireball. Default: true
	"Change Magispeller Fireball" = true
	#Whether or not to change the Magispeller's Fang Run. Default: true
	"Change Magispeller Fang Run" = true
	#Whether or not to change the Magispeller's Crashager. Default: true
	"Change Magispeller Crashager" = true
	#Whether or not to change the Magispeller's Fakers. Default: true
	"Change Magispeller Fakers" = true
	#Whether or not to change the Magispeller's Dispenser. Default: true
	"Change Magispeller Dispenser" = true

["Freakager & Ragno Settings (Unfinished)"]
	#The Freakager and Ragno's damage will be multiplied by this number. Default: 2.5
	"Freakager & Ragno Damage Multiplier" = 2.5
	#Whether or not the Freakager and Ragno wear armor. Default: true
	"Freakager & Ragno Wear Armor" = true

